name: 'Terraform CI'

on:
  push:
    branches: [ "main" ]
  pull_request:

# --- 1. PERMISOS OBLIGATORIOS PARA WIF ---
permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # --- 2. AUTENTICACIÃ“N SEGURA (Sin llaves JSON) ---
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          # Tu proveedor (El string que acabamos de conseguir)
          workload_identity_provider: 'projects/1098738077024/locations/global/workloadIdentityPools/github-pool-v3/providers/github-provider-final'
          # Tu Service Account (La que creamos en el script v3)
          service_account: 'github-ci-sa@gcp-devsecops-lab-483718.iam.gserviceaccount.com'

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # 4. Terraform Format
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # 5. Seguridad (tfsec)
      - name: Run tfsec security scanner
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true # Lo dejamos en true por ahora para ver el Plan

      # 6. Inicializar
      - name: Terraform Init
        run: terraform init
        working-directory: ./envs/dev

      # 7. Validar
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./envs/dev

      # 8. EL GRAN MOMENTO: Terraform Plan (Requiere credenciales)
      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./envs/dev
