name: 'Terraform CI'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform Sec & Quality'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # --- NUEVO PASO DE SEGURIDAD (DevSecOps) ---
    - name: Run tfsec security scanner
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working_directory: .
        soft_fail: false   # Queremos que falle si hay error
        additional_args: --force-all-dirs  # Escanea todo

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: ./envs/dev

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./envs/dev